CREATE TABLE aqi_data.aqi_readings (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL UNIQUE,
    pm25 DOUBLE PRECISION NOT NULL,
    pm10 DOUBLE PRECISION NOT NULL,
    aqi_pm25 INTEGER NOT NULL,
    aqi_pm10 INTEGER NOT NULL,
    overall_aqi INTEGER NOT NULL
);
